/*
 * Copyright 2026 Francesco Bilotta
 * Licensed under the Apache License, Version 2.0 (the "License").
 */
package com.iambilotta.spring.aiact.transparency;

import com.iambilotta.spring.aiact.annotation.AiActTransparency;
import com.iambilotta.spring.aiact.annotation.TransparencyKind;

/**
 * Resolved Article 50 transparency disclosure for an AI surface. Web-free on purpose: the
 * {@code core} module carries the disclosure model, the starter carries the servlet filter that
 * stamps {@link #headerName()} / {@link #headerValue()} on the HTTP response.
 *
 * <p>The header value is machine-detectable (a downstream agentic client can parse it without
 * reading prose) and carries the {@link TransparencyKind} token plus {@code article=50}.
 */
public record TransparencyDisclosure(TransparencyKind kind, String message) {

    /** Machine-detectable response header carrying the disclosure. */
    public static final String HEADER_NAME = "X-AiAct-Transparency";

    private static final String DEFAULT_INTERACTION =
            "You are interacting with an AI system.";
    private static final String DEFAULT_GENERATED_CONTENT =
            "This content was generated by an AI system.";

    /**
     * Resolve the disclosure declared by {@code @AiActTransparency} on {@code type}, or
     * {@code null} when the type does not declare it.
     */
    public static TransparencyDisclosure forType(Class<?> type) {
        AiActTransparency a = type.getAnnotation(AiActTransparency.class);
        if (a == null) {
            return null;
        }
        String message = a.disclosure().isBlank() ? defaultMessage(a.kind()) : a.disclosure();
        return new TransparencyDisclosure(a.kind(), message);
    }

    private static String defaultMessage(TransparencyKind kind) {
        return switch (kind) {
            case AI_INTERACTION -> DEFAULT_INTERACTION;
            case AI_GENERATED_CONTENT -> DEFAULT_GENERATED_CONTENT;
        };
    }

    public String headerName() {
        return HEADER_NAME;
    }

    /**
     * Machine-detectable value: the kind token plus the article reference, semicolon-separated.
     * Example: {@code ai-interaction; article=50}.
     */
    public String headerValue() {
        return kind.token() + "; article=50";
    }
}
