/*
 * Copyright 2026 Francesco Bilotta
 * Licensed under the Apache License, Version 2.0 (the "License").
 */
package com.iambilotta.spring.aiact.audit;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.iambilotta.spring.aiact.model.AuditEvent;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Spliterator;
import java.util.Spliterators;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.locks.ReentrantLock;
import java.util.stream.Stream;
import java.util.stream.StreamSupport;

/**
 * JDBC {@link AuditLogService}. Persists the append-only HMAC-chained Article 12 log to a single
 * relational table instead of a per-system NDJSON file, so the chain survives on ephemeral /
 * scale-to-zero runtimes where the local filesystem does not (REQ-AIACT-003).
 *
 * <p>The tamper-evidence property is identical to {@link NdjsonAuditLogService}: each record stores
 * the same canonical JSON (snake_case keys, deterministic) and the same {@code prev_hmac} /
 * {@code record_hmac}; {@link #verify} re-serialises each parsed event without its HMAC and walks
 * the chain in insertion order (the monotonic {@code seq} column), so any edit, reorder or deletion
 * of a stored row breaks verification at that row and every row linking back to it.
 *
 * <p>Chaining is serialised per {@code system_id} by an in-process {@link ReentrantLock} plus a
 * {@code SELECT ... FOR UPDATE} read of the current head under the same transaction, mirroring the
 * single-writer-lock guarantee of the NDJSON sink. Multi-writer correctness across JVMs relies on
 * the database row lock the transaction takes on the head read.
 */
public class JdbcAuditLogService implements AuditLogService {

    private static final String TABLE = "aiact_audit_log";

    private final DataSource dataSource;
    private final HmacChain hmac;
    private final ObjectMapper mapper;
    private final ConcurrentHashMap<String, ReentrantLock> locks = new ConcurrentHashMap<>();

    public JdbcAuditLogService(DataSource dataSource, HmacChain hmac, ObjectMapper mapper) {
        this.dataSource = dataSource;
        this.hmac = hmac;
        this.mapper = mapper;
    }

    /**
     * Create the audit table if it does not exist. Adopters who own their schema migration
     * (Flyway / Liquibase) should run the equivalent DDL there instead and skip this call; it is
     * provided so the sink is usable stand-alone and in tests. Idempotent.
     */
    public void initSchema() {
        try (Connection c = dataSource.getConnection(); Statement st = c.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS " + TABLE + " ("
                    + "seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "
                    + "system_id VARCHAR(255) NOT NULL, "
                    + "event_ts TIMESTAMP NOT NULL, "
                    + "prev_hmac VARCHAR(64) NOT NULL, "
                    + "record_hmac VARCHAR(64) NOT NULL, "
                    + "record_json CLOB NOT NULL)");
            st.execute("CREATE INDEX IF NOT EXISTS idx_" + TABLE + "_system "
                    + "ON " + TABLE + " (system_id, seq)");
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot create audit table " + TABLE, e);
        }
    }

    @Override
    public AuditEvent append(AuditEvent event) {
        String systemId = event.systemId();
        if (systemId == null || systemId.isBlank()) {
            throw new IllegalArgumentException("AuditEvent.systemId is mandatory");
        }
        ReentrantLock lock = locks.computeIfAbsent(systemId, k -> new ReentrantLock());
        lock.lock();
        try (Connection c = dataSource.getConnection()) {
            c.setAutoCommit(false);
            try {
                String prev = headHmacForUpdate(c, systemId);
                AuditEvent sealed = sealWithChain(event, prev);
                insert(c, sealed);
                c.commit();
                return sealed;
            } catch (SQLException e) {
                c.rollback();
                throw e;
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot append audit event for " + systemId, e);
        } finally {
            lock.unlock();
        }
    }

    private String headHmacForUpdate(Connection c, String systemId) throws SQLException {
        String sql = "SELECT record_hmac FROM " + TABLE
                + " WHERE system_id = ? ORDER BY seq DESC FETCH FIRST 1 ROWS ONLY FOR UPDATE";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, systemId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    String h = rs.getString(1);
                    return h == null || h.isBlank() ? HmacChain.CHAIN_SEED : h;
                }
            }
        }
        return HmacChain.CHAIN_SEED;
    }

    private void insert(Connection c, AuditEvent sealed) throws SQLException {
        String sql = "INSERT INTO " + TABLE
                + " (system_id, event_ts, prev_hmac, record_hmac, record_json) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, sealed.systemId());
            ps.setTimestamp(2, Timestamp.from(sealed.timestamp() == null ? Instant.now() : sealed.timestamp()));
            ps.setString(3, sealed.prevHmac());
            ps.setString(4, sealed.recordHmac());
            ps.setString(5, serialize(sealed));
            ps.executeUpdate();
        }
    }

    private AuditEvent sealWithChain(AuditEvent event, String prev) {
        String payload = serializeWithoutHmac(event);
        String mac = hmac.chain(prev, payload);
        return new AuditEvent(
                event.eventId(), event.eventKind(), event.timestamp(), event.systemId(),
                event.systemVersion(), event.operation(), event.userIdPseudonymized(),
                event.modelId(), event.inputHash(), event.outputHash(), event.hashAlgorithm(),
                event.latencyMs(), event.dbReference(), event.verifierId(),
                event.linkedEventId(), event.correlationId(), event.metadata(),
                prev, mac
        );
    }

    @Override
    public Stream<AuditEvent> stream(String systemId, Instant from, Instant to) {
        List<AuditEvent> events = new ArrayList<>();
        String sql = "SELECT record_json FROM " + TABLE + " WHERE system_id = ? ORDER BY seq ASC";
        try (Connection c = dataSource.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, systemId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    AuditEvent e = parse(rs.getString(1));
                    if (e != null && within(e.timestamp(), from, to)) {
                        events.add(e);
                    }
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot read audit log for " + systemId, e);
        }
        return StreamSupport.stream(
                Spliterators.spliterator(events, Spliterator.ORDERED), false);
    }

    @Override
    public ChainVerification verify(String systemId, Instant from, Instant to) {
        long inspected = 0;
        long invalid = 0;
        List<String> failures = new ArrayList<>();
        String prev = HmacChain.CHAIN_SEED;
        String sql = "SELECT record_json FROM " + TABLE + " WHERE system_id = ? ORDER BY seq ASC";
        try (Connection c = dataSource.getConnection();
             PreparedStatement ps = c.prepareStatement(sql)) {
            ps.setString(1, systemId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) {
                    AuditEvent event = parse(rs.getString(1));
                    if (event == null) continue;
                    boolean inRange = within(event.timestamp(), from, to);
                    if (inRange) inspected++;
                    String payload = serializeWithoutHmac(event);
                    boolean ok = hmac.verify(prev, payload, event.recordHmac())
                            && safeEquals(prev, event.prevHmac());
                    if (!ok && inRange) {
                        invalid++;
                        failures.add(String.valueOf(event.eventId()));
                    }
                    prev = event.recordHmac();
                }
            }
        } catch (SQLException e) {
            throw new IllegalStateException("Cannot verify audit log for " + systemId, e);
        }
        return new ChainVerification(systemId, from, to, inspected, invalid, failures);
    }

    @Override
    public void writeJsonLine(java.io.Writer w, AuditEvent event) throws java.io.IOException {
        w.write(serialize(event));
        w.write('\n');
    }

    private String serialize(AuditEvent event) {
        try {
            return mapper.writeValueAsString(event);
        } catch (Exception e) {
            throw new IllegalStateException("Cannot serialize audit event " + event.eventId(), e);
        }
    }

    private String serializeWithoutHmac(AuditEvent event) {
        AuditEvent canonical = new AuditEvent(
                event.eventId(), event.eventKind(), event.timestamp(), event.systemId(),
                event.systemVersion(), event.operation(), event.userIdPseudonymized(),
                event.modelId(), event.inputHash(), event.outputHash(), event.hashAlgorithm(),
                event.latencyMs(), event.dbReference(), event.verifierId(),
                event.linkedEventId(), event.correlationId(), event.metadata(),
                null, null
        );
        return serialize(canonical);
    }

    private AuditEvent parse(String json) {
        try {
            return mapper.readValue(json, AuditEvent.class);
        } catch (Exception e) {
            throw new IllegalStateException("Cannot parse stored audit record", e);
        }
    }

    private static boolean within(Instant ts, Instant from, Instant to) {
        if (ts == null) return false;
        if (from != null && ts.isBefore(from)) return false;
        if (to != null && ts.isAfter(to)) return false;
        return true;
    }

    private static boolean safeEquals(String a, String b) {
        if (a == null || b == null) return false;
        if (a.length() != b.length()) return false;
        int diff = 0;
        for (int i = 0; i < a.length(); i++) diff |= a.charAt(i) ^ b.charAt(i);
        return diff == 0;
    }
}
