/*
 * Copyright 2026 Francesco Bilotta
 * Licensed under the Apache License, Version 2.0 (the "License").
 */
package com.iambilotta.spring.aiact.codegen.datasheet;

import com.iambilotta.spring.aiact.codegen.model.TechnicalFileModel;

import java.util.List;

/**
 * Renders one Markdown datasheet per dataset, structured around the AI Act Article 10 disclosure
 * requirements (provenance, intended use, biases, governance) and the Datasheets for Datasets
 * framework (Gebru et al., 2018). The renderer never invents content: missing values are surfaced
 * as visible placeholders so reviewers can see the gap.
 */
public final class DatasetDatasheetRenderer {

    private static final String GAP =
            "_Not declared. Update the @AiActDataset annotation or the data governance record._";

    public String render(TechnicalFileModel.DatasetEntry d, String systemId) {
        StringBuilder sb = new StringBuilder(2 * 1024);
        sb.append("# Dataset datasheet, `").append(d.id()).append("`\n\n");
        sb.append("**System:** `").append(systemId).append("`  \n");
        sb.append("**Dataset name:** ").append(safe(d.name())).append("  \n");
        sb.append("**Phase:** ").append(safe(d.phase())).append("  \n");
        sb.append("**License:** ").append(safe(d.license())).append("  \n");
        sb.append("**Personal data (GDPR Article 4(1)):** ").append(d.personalData() ? "yes" : "no")
                .append("\n\n");

        section(sb, "Provenance",
                "**Source:** " + safe(d.source()) + "  \n"
                        + "**Approximate size:** " + safe(d.size()));

        section(sb, "Article 10 governance",
                "- The dataset is used in the {phase} phase of the AI system lifecycle.\n"
                        .replace("{phase}", safe(d.phase()))
                        + "- Personal data: " + (d.personalData() ? "yes" : "no")
                        + (d.personalData() ? ", a separate Article 35 DPIA is required."
                                              : ", outside the scope of GDPR Article 35.")
                        + "\n");

        section(sb, "Documented biases and representational gaps",
                d.biases() == null || d.biases().isEmpty()
                        ? "_No biases formally measured at the time of this build._"
                        : bullets(d.biases()));

        section(sb, "Recommended uses",
                "_Free-form, fill from data governance record._\n\n" + GAP);

        section(sb, "Recommended non-uses",
                "_Free-form, fill from data governance record._\n\n" + GAP);

        section(sb, "Maintenance",
                "_Owner, refresh cadence, retirement plan._\n\n" + GAP);

        sb.append("---\n\n");
        sb.append("_Generated by spring-aiact._\n");
        return sb.toString();
    }

    private static void section(StringBuilder sb, String title, String body) {
        sb.append("## ").append(title).append("\n\n").append(body).append("\n\n");
    }

    private static String bullets(List<String> items) {
        StringBuilder sb = new StringBuilder();
        for (String s : items) sb.append("- ").append(s).append('\n');
        return sb.toString();
    }

    private static String safe(String s) {
        return s == null || s.isBlank() ? "_unspecified_" : s;
    }
}
